# Generated by Django 4.2.13 on 2024-08-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catName',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
