# Generated by Django 4.2.13 on 2024-08-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_catname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catName',
            field=models.CharField(default='Sports', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='Sports', max_length=255),
        ),
    ]
