# Generated by Django 4.2.13 on 2024-07-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_alter_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.TextField(max_length=1000000),
        ),
    ]
