# Generated by Django 4.2.13 on 2024-07-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_rename_chatroom_chatrooms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chatrooms',
            new_name='Rooms',
        ),
    ]
